### ISSUE TITLE
Doctrine embedded stopped working when upgrading from 1.3 to 3.0

### ISSUE THREAD

**Issue by garak** [moneyphp/money#324]
I'm using this library with Doctrine. Here is my mapping:
``` yaml
Money\Money:
    type: embeddable
    embedded:
        currency:
            class: Money\Currency
    fields:
        amount:
            type: integer
```
``` yaml
Money\Currency:
    type: embeddable
    fields:
        name:
            length: 3
```
This is working fine in 1.3. In 3.0, instead, I'm getting an exception: `
Infinite nesting detected for embedded property MyEntity::foo. You cannot embed an embeddable from the same type inside an embeddable.` (where `foo` is a property mapped as embedded Money).
