### ISSUE TITLE
Documentation: Doctrine embeddables

### ISSUE THREAD

**Issue by foaly-nr1** [moneyphp/money#327]
This class can easily be mapped to a relational database table using Doctrine embeddables. Worth mentioning in the docs?

```yaml
# When using Symfony: app/Resources/Money/doctrine/Money.orm.yml
Money\Money:
  type: embeddable
  fields:
    amount:
      type: integer
  embedded:
    currency:
      class: Money\Currency
```

```yaml
# When using Symfony: app/Resources/Money/doctrine/Currency.orm.yml
Money\Currency:
  type: embeddable
  fields:
    code:
      type: string
      length: 3
```

```yaml
# When using Symfony: app/config.yml
doctrine:
  orm:
    mappings:
      Money:
        type: yml
        dir: "%kernel.root_dir%/../app/Resources/Money/doctrine"
        prefix: Money
```
