### ISSUE TITLE
Doctrine documentation

### ISSUE THREAD

**Issue by webmake** [moneyphp/money#504]
Recently, I had an issue due insufficient documentation with doctrine integration, so added mapping intuitively:
```
Money\Money:
    type: embeddable
    fields:
        amount:
            name: amount
            type: integer
    embedded:
        currency:
            class: Money\Currency
```
Everything worked fine, but from database amount value is set to object as integer (?!), so making Money object by hand, those two values are not equal
`$product->getPrice()->equals(new \Money\Money($product->getPrice()->getAmount(), new \Money\Currency($product->getPrice()->getCurrency()->getCode())))`

Strange but in [discussion](https://github.com/moneyphp/money/issues/328) was valid mapping yaml, so I think it deserved to be mentioned about integration with doctrine..
```
Money\Money:
    type: embeddable
    fields:
        amount:
            name: amount
            type: string
    embedded:
        currency:
            class: Money\Currency
```
